[package]
name = "fhe"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
bincode = "1.3.3"
risc0-zkvm = { version = "1.0.1", default-features = false, features = ['std', 'getrandom'] }
tfhe = { path = "../../../tfhe-rs/tfhe", features = ["boolean", "zkvm"] }